### ISSUE TITLE
It is not possible to use dalli (or memcache) store

### ISSUE THREAD

**Issue by fabioperrella** [locaweb/cassette#30]
When I tried to set the cache store using the gem `dalli` or `ActiveSupport::Cache::MemCacheStore.new` , I've got the error below:

```
# with dalli:
NoMethodError:
  undefined method `delete_matched' for #<ActiveSupport::Cache::DalliStore:0x005563ce39f828>
  .rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/cassette-1.2.4/lib/cassette/client/cache.rb:38:in `clear_st_cache!'

# with MemCacheStore
NotImplementedError:
  ActiveSupport::Cache::MemCacheStore does not support delete_matched
```

So I think something must be done to support Memcache store or change the Readme to say it does not support Memcache store.

wdyt?

**Comment by rhruiz** [comment]
I think we can create the warning for now and maybe find a way around having to delete STs from the cache when the TGT is deleted. Maybe  use a hash of the tgt value  as part of the cache key for ST?s?

**Comment by rgaufman** [comment]
Is there any workaround to achieve the same with MemCacheStore?

**Comment by TecnoSigma** [comment]
Hi @rgaufman,

So that we don't create a thread in a finished issue, you can expose your problem in a new issue.


Thanks.
